const {chromium}=require(process.env.PWPATH||'playwright');
require('fs').mkdirSync(__dirname+'/shots',{recursive:true});
(async()=>{
  const b=await chromium.launch();const p=await b.newPage({viewport:{width:1280,height:800}});
  const errs=[];p.on('pageerror',e=>errs.push('PE '+e.message+' '+(e.stack||'').split('\n')[1]));p.on('console',m=>{if(m.type()==='error')errs.push('CE '+m.text())});
  p.on('dialog',d=>d.accept('테스트'));
  await p.goto('file://'+require('path').resolve(__dirname,'../dist/gangho.html'));await p.waitForTimeout(3000);
  await p.evaluate(()=>localStorage.clear());
  await p.click('[data-s="new"]');await p.click('[data-s="side:사"]');await p.click('[data-s="cls:궁"]');await p.click('[data-s="start"]');await p.waitForTimeout(800);
  const step=async(name,fn,wait=300)=>{try{const r=await p.evaluate(fn);console.log(name,JSON.stringify(r))}catch(e){console.log(name,'ERR',e.message)}await p.waitForTimeout(wait)};
  await step('read',()=>{readBook(P.bag.find(i=>i.slot==='book'));return{cur:P.cur,art:art().n,cls:curCls(),weapon:P.eq.weapon&&P.eq.weapon.name}});
  await step('fight',()=>{P.x=29.5;P.y=21.5;P.vit+=2000;P.target=nearest(20);return P.target&&P.target.name},6000);
  await p.screenshot({path:__dirname+'/shots/s2_bow.png'});
  await step('after',()=>({kills:P.kills,hp:Math.round(P.hp),vit:P.vit,drops:drops.length}));
  await step('qi',()=>{mobs.forEach(m=>m.aggro=false);P.x=20.5;P.y=20.5;trainQi();return P.chan&&P.chan.label},2000);
  await step('qi2',()=>({qiN:P.qiN,maxQi:P.maxQi}));
  await step('stat',()=>{trainStat('str');return P.st.str});
  await step('learn all',()=>{const a=art();A(a.id).p=100;a.forms.forEach((f,i)=>{if(!A(a.id).f[i])readBook(mkBook(a.id,i))});return A(a.id).f});
  await step('ult',()=>{P.x=29.5;P.y=21.5;P.qi=P.maxQi;P.target=nearest(20);ultimate();return P.ucd},1500);
  await p.screenshot({path:__dirname+'/shots/s2_ult.png'});
  await step('combo',()=>{P.qi=P.maxQi;P.fcd=[0,0,0,0,0,0];useForm(0);return P.chain},300);
  await step('combo2',()=>{P.gcd=0;useForm(1);return P.chain},300);
  await step('specials',()=>{P.sp={암기:1,독공:1,점혈:1};P.mats.비도=5;P.qi=P.maxQi;special('암기');special('독공');return P.scd});
  await step('tame',()=>{const w=mobs.find(m=>m.kind==='늑대'||m.kind==='말'||m.kind==='사슴');if(!w)return'none';P.x=w.x+.5;P.y=w.y;P.vit+=500;P.qiBonus+=500;recalc();for(let i=0;i<5&&mobs.includes(w);i++)tame(w);return{allies:allies.map(a=>a.name)}},1500);
  await step('horse',()=>{const h=mkAlly('pet','말',P.x,P.y);allies.push(h);rideToggle();return{ride:!!P.ride,spd:moveSpd()}},1500);
  await p.screenshot({path:__dirname+'/shots/s2_ride.png'});
  await step('gather',()=>{rideToggle();const n=nodes.find(n=>n.t==='herb');P.x=n.x;P.y=n.y;interact({node:n});return P.chan&&P.chan.label},1600);
  await step('mats',()=>P.mats);
  await step('farm',()=>{P.mats.볍씨=2;const pl=plots[0];plotAction(pl);pl.g=1;plotAction(pl);return P.mats.쌀});
  await step('craft',()=>{P.jobs.약재.on=1;P.mats.약초=10;craft(RECIPES.find(r=>r.n==='금창약'));P.jobs.대장.on=1;P.mats.광석=10;P.mats.목재=10;P.mats.가죽=5;P.x=23.5;P.y=18.5;craft(RECIPES.find(r=>r.n.startsWith('각궁')));return{bag:P.bag.map(i=>i.name),lv:P.jobs.대장.lv}});
  await step('shop',()=>{P.silver=2000;openNpc(npcAt('gen'));act('buy:gen:4');act('buy:gen:0');return{bag:P.bag.length,seed:P.mats.볍씨}});
  await p.screenshot({path:__dirname+'/shots/s2_shop.png'});
  await step('sect',()=>{closePanels();openNpc(npcAt('sa'));act('join:사');renderOpen();return P.sect});
  await p.screenshot({path:__dirname+'/shots/s2_sect.png'});
  await step('board',()=>{closePanels();openNpc(npcAt('board'));act('qtake:0');return P.quests.map(q=>q.n)});
  await step('marry',()=>{closePanels();P.age=19;P.fame=50;openNpc(npcAt('mae'));act('marry');return P.spouse});
  await step('house',()=>{closePanels();openNpc(npcAt('land'));act('lot:0');act('build');closePanels();return G.house});
  await step('duel',()=>{openNpc(npcAt('arena'));act('duel');return G.duel},3000);
  await p.screenshot({path:__dirname+'/shots/s2_duel.png'});
  await step('duelres',()=>{const e=mobs.find(m=>m.duel);if(e){e.hp=1;damage(e,5)}return{duel:G.duel,won:P.duel}});
  await step('panels',()=>{for(const k of['char','arts','bag','ally','life','hist','house','help']){openPanel(k);closePanels()}return 'ok'});
  await step('year',()=>{for(let i=0;i<6;i++){P.age+=1;newYear()}return{age:P.age,kids:P.children}});
  await step('save',()=>{saveGame();return localStorage.getItem(SAVE_KEY).length});
  await p.screenshot({path:__dirname+'/shots/s2_world.png'});
  await step('die',()=>{P.children.push({name:'후계',age:3});die('전투');return G.history.length},1500);
  await p.screenshot({path:__dirname+'/shots/s2_rebirth.png'});
  await p.click('[data-s="rebirth"]');await p.waitForTimeout(300);await p.screenshot({path:__dirname+'/shots/s2_create2.png'});
  await p.click('[data-s="heir:0"]');await p.click('[data-s="start"]');await p.waitForTimeout(1000);
  await step('life2',()=>({name:P.name,status:P.status,vit:P.vit,house:G.house,lifeNo:P.lifeNo,builds:builds.filter(b=>b.home).length}));
  await p.reload();await p.waitForTimeout(2500);await p.click('[data-s="cont"]');await p.waitForTimeout(800);
  await step('loaded',()=>({name:P.name,age:P.age,playing}));
  await p.screenshot({path:__dirname+'/shots/s2_loaded.png'});
  console.log(errs.join('\n'));
  await b.close();
})();
